NHSISL/ISL.ReIdentification

ISL.Reidentification.Core/Brokers/Storages/Sql/Reidentifications/IReidentificationStorageBroker.DelegatedAccess.cs
ISL.Reidentification.Core/Brokers/Storages/Sql/Reidentifications/ReidentificationStorageBroker.DelegatedAccess.Configurations.cs
ISL.Reidentification.Core/Brokers/Storages/Sql/Reidentifications/ReidentificationStorageBroker.DelegatedAccess.cs
ISL.Reidentification.Core/Brokers/Storages/Sql/Reidentifications/ReidentificationStorageBroker.cs
ISL.Reidentification.Core/Migrations/20240909115707_AddDelegatedAccess.Designer.cs
ISL.Reidentification.Core/Migrations/20240909115707_AddDelegatedAccess.cs
ISL.Reidentification.Core/Models/Foundations/DelegatedAccesses/DelegatedAccess.cs

DATA: DelegatedAccess

---

ISL.Reidentification.Core.Tests.Unit/Services/Foundations/DelegatedAccesses/DelegatedAccessesTests.Validations.Add.cs
ISL.Reidentification.Core.Tests.Unit/Services/Foundations/DelegatedAccesses/DelegatedAccessesTests.cs
ISL.Reidentification.Core/Services/Foundations/DelegatedAccesses/DelegatedAccessService.Validations.Add.cs

FOUNDATIONS: DelegatedAccess Add Length Validation

---

ISL.ReIdentification.Core/Brokers/Storages/Sql/ReIdentifications/IReIdentificationStorageBroker.Lookups.cs
ISL.ReIdentification.Core/Brokers/Storages/Sql/ReIdentifications/ReIdentificationStorageBroker.Lookups.cs

BROKERS: Lookups

---

ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/UserAccesses/UserAccessesTests.cs
ISL.ReIdentification.Core/Brokers/Storages/Sql/ReIdentifications/IReidentificationStorageBroker.UserAccess.cs
ISL.ReIdentification.Core/Brokers/Storages/Sql/ReIdentifications/ReidentificationStorageBroker.UserAccess.cs
ISL.ReIdentification.Core/Services/Foundations/UserAccesses/IUserAccessService.cs
ISL.ReIdentification.Core/Services/Foundations/UserAccesses/UserAccessService.Exceptions.cs
ISL.ReIdentification.Core/Services/Foundations/UserAccesses/UserAccessService.cs
ISL.Reidentification.Core.Tests.Unit/Services/Foundations/UserAccesses/UserAccessesTests.Exceptions.RetrieveAll.cs
ISL.Reidentification.Core.Tests.Unit/Services/Foundations/UserAccesses/UserAccessesTests.Logic.RetrieveAll.cs

FOUNDATIONS: UserAccess Retrieve All

---

ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/DelegatedAccesses/DelegatedAccessesTests.Exceptions.RetrieveAll.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/DelegatedAccesses/DelegatedAccessesTests.Logic.RetrieveAll.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/DelegatedAccesses/DelegatedAccessesTests.cs
ISL.ReIdentification.Core/Services/Foundations/DelegatedAccesses/DelegatedAccessService.Exceptions.cs
ISL.ReIdentification.Core/Services/Foundations/DelegatedAccesses/DelegatedAccessService.cs
ISL.ReIdentification.Core/Services/Foundations/DelegatedAccesses/IDelegatedAccessService.cs

FOUNDATIONS: DelegatedAccess Retrieve All

---

ISL.ReIdentification.Core/Services/Foundations/UserAccesses/IUserAccessService.cs
ISL.ReIdentification.Core/Services/Foundations/UserAccesses/UserAccessService.Validations.cs
ISL.ReIdentification.Core/Services/Foundations/UserAccesses/UserAccessService.cs
ISL.Reidentification.Core.Tests.Unit/Services/Foundations/UserAccesses/UserAccessesTests.Exceptions.RetrieveById.cs
ISL.Reidentification.Core.Tests.Unit/Services/Foundations/UserAccesses/UserAccessesTests.Logic.RetrieveById.cs
ISL.Reidentification.Core.Tests.Unit/Services/Foundations/UserAccesses/UserAccessesTests.Validations.RetrieveById.cs

FOUNDATIONS: UserAccess RetrieveById

---

ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Unit/Controllers/DelegatedAccesses/DelegatedAccessesControllerTests.GetAll.cs
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Unit/Controllers/DelegatedAccesses/DelegatedAccessesControllerTests.cs
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server/Controllers/DelegatedAccessesController.cs

CONTROLLERS: DelegatedAccess GetAll

---

ISL.Reidentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Unit/Controllers/UserAccesses/UserAccessesControllerTests.Get.cs
ISL.Reidentification.WebApps.Configurations/ISL.Reidentification.Configurations.Server/Controllers/UserAccessesController.cs

CONTROLLERS: UserAccess Get

---

ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Unit/Controllers/DelegatedAccesses/DelegatedAccessesControllerTests.Get.cs
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server/Controllers/DelegatedAccessesController.cs

CONTROLLERS: DelegatedAccess Get

---

ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Unit/Controllers/DelegatedAccesses/DelegatedAccessesControllerTests.Put.cs
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server/Controllers/DelegatedAccessesController.cs

CONTROLLERS: DelegatedAccess Put

---

ISL.Reidentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Unit/Controllers/UserAccesses/UserAccessesControllerTests.Put.cs
ISL.Reidentification.WebApps.Configurations/ISL.Reidentification.Configurations.Server/Controllers/UserAccessesController.cs

CONTROLLERS: UserAccess Put

---

ISL.Reidentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Unit/Controllers/UserAccesses/UserAccessesControllerTests.Delete.cs
ISL.Reidentification.WebApps.Configurations/ISL.Reidentification.Configurations.Server/Controllers/UserAccessesController.cs

CONTROLLERS: UserAccess Delete

---

ISL.ReIdentification.Core/Models/Foundations/OdsDatas/Exceptions/FailedServiceOdsDataException.cs
ISL.ReIdentification.Core/Models/Foundations/OdsDatas/Exceptions/FailedStorageOdsDataException.cs
ISL.ReIdentification.Core/Models/Foundations/OdsDatas/Exceptions/OdsDataDependencyException.cs
ISL.ReIdentification.Core/Models/Foundations/OdsDatas/Exceptions/OdsDataServiceException.cs
ISL.ReIdentification.Core/Services/Foundations/Ods/IOdsService.cs
ISL.ReIdentification.Core/Services/Foundations/Ods/OdsService.Exceptions.cs
ISL.ReIdentification.Core/Services/Foundations/Ods/OdsService.cs
ISL.Reidentification.Core.Tests.Unit/Services/Foundations/Ods/OdsTests.Exceptions.RetrieveAll.cs
ISL.Reidentification.Core.Tests.Unit/Services/Foundations/Ods/OdsTests.Logic.RetrieveAll.cs
ISL.Reidentification.Core.Tests.Unit/Services/Foundations/Ods/OdsTests.cs

FOUNDATIONS: OdsData Retrieve All

---

ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Unit/Controllers/DelegatedAccesses/DelegatedAccessesControllerTests.Delete.cs
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server/Controllers/DelegatedAccessesController.cs

CONTROLLERS: DelegatedAccess Delete

---

ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Acceptance/Apis/DelegatedAccessesApiTests.Logic.cs
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Acceptance/Apis/DelegatedAccessesApiTests.cs

ACCEPTANCE: DelegatedAccess GetById

---

ISL.Reidentification.WebApps.Configurations/ISL.Reidentification.Configurations.Server.Tests.Acceptance/Apis/UserAccessesApiTests.Logic.cs
ISL.Reidentification.WebApps.Configurations/ISL.Reidentification.Configurations.Server.Tests.Acceptance/Apis/UserAccessesApiTests.cs
ISL.Reidentification.WebApps.Configurations/ISL.Reidentification.Configurations.Server.Tests.Acceptance/Brokers/ApiBroker.UserAccesses.cs
ISL.Reidentification.WebApps.Configurations/ISL.Reidentification.Configurations.Server.Tests.Acceptance/Models/Lookups/UserAccess.cs

ACCEPTANCE: UserAccess Post

---

ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Acceptance/Apis/DelegatedAccessesApiTests.Logic.cs
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Acceptance/Apis/DelegatedAccessesApiTests.cs
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Acceptance/Brokers/ApiBroker.DelegatedAccesses.cs

ACCEPTANCE: DelegatedAccess Put

---

ISL.ReIdentification.Core/Models/Foundations/OdsDatas/Exceptions/InvalidOdsDataException.cs
ISL.ReIdentification.Core/Models/Foundations/OdsDatas/Exceptions/NotFoundOdsDataException.cs
ISL.ReIdentification.Core/Models/Foundations/OdsDatas/Exceptions/OdsDataValidationException.cs
ISL.ReIdentification.Core/Services/Foundations/OdsDatas/IOdsDataService.cs
ISL.ReIdentification.Core/Services/Foundations/OdsDatas/OdsDataService.Exceptions.cs
ISL.ReIdentification.Core/Services/Foundations/OdsDatas/OdsDataService.Validations.cs
ISL.ReIdentification.Core/Services/Foundations/OdsDatas/OdsDataService.cs
ISL.Reidentification.Core.Tests.Unit/Services/Foundations/OdsDatas/OdsDataServiceTests.Exceptions.RetrieveAll.cs
ISL.Reidentification.Core.Tests.Unit/Services/Foundations/OdsDatas/OdsDataServiceTests.Exceptions.RetrieveById.cs
ISL.Reidentification.Core.Tests.Unit/Services/Foundations/OdsDatas/OdsDataServiceTests.Logic.RetrieveAll.cs
ISL.Reidentification.Core.Tests.Unit/Services/Foundations/OdsDatas/OdsDataServiceTests.Logic.RetrieveById.cs
ISL.Reidentification.Core.Tests.Unit/Services/Foundations/OdsDatas/OdsDataServiceTests.Validations.RetrieveById.cs
ISL.Reidentification.Core.Tests.Unit/Services/Foundations/OdsDatas/OdsDataServiceTests.cs

FOUNDATIONS: OdsData Retrieve By Id

---

ISL.Reidentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Unit/Controllers/OdsDatas/OdsDataControllerTests.Get.cs
ISL.Reidentification.WebApps.Configurations/ISL.Reidentification.Configurations.Server/Controllers/OdsDataController.cs

CONTROLLERS: OdsData Get

---

ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/PdsDatas/PdsDataServiceTests.Exceptions.RetrieveAll.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/PdsDatas/PdsDataServiceTests.Exceptions.RetrieveById.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/PdsDatas/PdsDataServiceTests.Logic.RetrieveAll.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/PdsDatas/PdsDataServiceTests.Logic.RetrieveById.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/PdsDatas/PdsDataServiceTests.Validations.RetrieveById.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/PdsDatas/PdsDataServiceTests.cs
ISL.ReIdentification.Core/Brokers/Storages/Sql/PatientOrgReference/IPatientOrgReferenceStorageBroker.OdsData.cs
ISL.ReIdentification.Core/Brokers/Storages/Sql/PatientOrgReference/IPatientOrgReferenceStorageBroker.PdsData.cs
ISL.ReIdentification.Core/Brokers/Storages/Sql/PatientOrgReference/IPatientOrgReferenceStorageBroker.cs
ISL.ReIdentification.Core/Brokers/Storages/Sql/PatientOrgReference/MockPatientOrgReferenceStorageBroker.OdsData.cs
ISL.ReIdentification.Core/Brokers/Storages/Sql/PatientOrgReference/MockPatientOrgReferenceStorageBroker.cs
ISL.ReIdentification.Core/Brokers/Storages/Sql/PatientOrgReference/PatientOrgReferenceStorageBroker.OdsData.cs
ISL.ReIdentification.Core/Brokers/Storages/Sql/PatientOrgReference/PatientOrgReferenceStorageBroker.PdsData.cs
ISL.ReIdentification.Core/Brokers/Storages/Sql/PatientOrgReference/PatientOrgReferenceStorageBroker.cs
ISL.ReIdentification.Core/Services/Foundations/OdsDatas/OdsDataService.cs
ISL.ReIdentification.Core/Services/Foundations/PdsDatas/PdsDataService.cs
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server/Program.cs
ISL.Reidentification.Core.Tests.Unit/Services/Foundations/OdsDatas/OdsDataServiceTests.Exceptions.RetrieveAll.cs
ISL.Reidentification.Core.Tests.Unit/Services/Foundations/OdsDatas/OdsDataServiceTests.Exceptions.RetrieveById.cs
ISL.Reidentification.Core.Tests.Unit/Services/Foundations/OdsDatas/OdsDataServiceTests.Logic.RetrieveAll.cs
ISL.Reidentification.Core.Tests.Unit/Services/Foundations/OdsDatas/OdsDataServiceTests.Logic.RetrieveById.cs
ISL.Reidentification.Core.Tests.Unit/Services/Foundations/OdsDatas/OdsDataServiceTests.Validations.RetrieveById.cs
ISL.Reidentification.Core.Tests.Unit/Services/Foundations/OdsDatas/OdsDataServiceTests.cs
ISL.Reidentification.WebApps.Configurations/ISL.Reidentification.Configurations.Server.Tests.Acceptance/Brokers/AcceptanceTestApplicationFactory.cs

BROKERS: Ods - Refactor

---

ISL.ReIdentification.Core.Tests.Unit/Services/Processings/UserAccesses/UserAccessProcessingServiceTests.Exceptions.AddUserAccess.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Processings/UserAccesses/UserAccessProcessingServiceTests.Exceptions.RetrieveAllUserAccesses.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Processings/UserAccesses/UserAccessProcessingServiceTests.Logic.AddUserAccess.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Processings/UserAccesses/UserAccessProcessingServiceTests.Logic.RetrieveAllUserAccesses.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Processings/UserAccesses/UserAccessProcessingServiceTests.Validation.AddUserAccess.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Processings/UserAccesses/UserAccessProcessingServiceTests.cs
ISL.ReIdentification.Core/Models/Foundations/UserAccesses/BulkUserAccess.cs
ISL.ReIdentification.Core/Models/Processings/UserAccesses/Exceptions/FailedUserAccessProcessingServiceException.cs
ISL.ReIdentification.Core/Models/Processings/UserAccesses/Exceptions/NullUserAccessProcessingException.cs
ISL.ReIdentification.Core/Models/Processings/UserAccesses/Exceptions/UserAccessProcessingDependencyException.cs
ISL.ReIdentification.Core/Models/Processings/UserAccesses/Exceptions/UserAccessProcessingDependencyValidationException.cs
ISL.ReIdentification.Core/Models/Processings/UserAccesses/Exceptions/UserAccessProcessingServiceException.cs
ISL.ReIdentification.Core/Models/Processings/UserAccesses/Exceptions/UserAccessProcessingValidationException.cs
ISL.ReIdentification.Core/Services/Processings/UserAccesses/IUserAccessProcessingService.cs
ISL.ReIdentification.Core/Services/Processings/UserAccesses/UserAccessProcessingService.Exceptions.cs
ISL.ReIdentification.Core/Services/Processings/UserAccesses/UserAccessProcessingService.Validations.cs
ISL.ReIdentification.Core/Services/Processings/UserAccesses/UserAccessProcessingService.cs
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server/Program.cs
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server/Program.cs

PROCESSINGS: User Access - Retrieve All User Accesses

---

ISL.ReIdentification.Core.Tests.Unit/Services/Processings/UserAccesses/UserAccessProcessingServiceTests.Exceptions.AddUserAccess.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Processings/UserAccesses/UserAccessProcessingServiceTests.Exceptions.RetrieveAllUserAccesses.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Processings/UserAccesses/UserAccessProcessingServiceTests.Exceptions.RetrieveUserAccessById.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Processings/UserAccesses/UserAccessProcessingServiceTests.Logic.AddUserAccess.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Processings/UserAccesses/UserAccessProcessingServiceTests.Logic.RetrieveAllUserAccesses.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Processings/UserAccesses/UserAccessProcessingServiceTests.Logic.RetrieveUserAccessById.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Processings/UserAccesses/UserAccessProcessingServiceTests.Validation.AddUserAccess.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Processings/UserAccesses/UserAccessProcessingServiceTests.Validation.RetrieveUserAccessById.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Processings/UserAccesses/UserAccessProcessingServiceTests.cs
ISL.ReIdentification.Core/Models/Foundations/UserAccesses/BulkUserAccess.cs
ISL.ReIdentification.Core/Models/Processings/UserAccesses/Exceptions/FailedUserAccessProcessingServiceException.cs
ISL.ReIdentification.Core/Models/Processings/UserAccesses/Exceptions/InvalidUserAccessProcessingException.cs
ISL.ReIdentification.Core/Models/Processings/UserAccesses/Exceptions/NullUserAccessProcessingException.cs
ISL.ReIdentification.Core/Models/Processings/UserAccesses/Exceptions/UserAccessProcessingDependencyException.cs
ISL.ReIdentification.Core/Models/Processings/UserAccesses/Exceptions/UserAccessProcessingDependencyValidationException.cs
ISL.ReIdentification.Core/Models/Processings/UserAccesses/Exceptions/UserAccessProcessingServiceException.cs
ISL.ReIdentification.Core/Models/Processings/UserAccesses/Exceptions/UserAccessProcessingValidationException.cs
ISL.ReIdentification.Core/Services/Processings/UserAccesses/IUserAccessProcessingService.cs
ISL.ReIdentification.Core/Services/Processings/UserAccesses/UserAccessProcessingService.Exceptions.cs
ISL.ReIdentification.Core/Services/Processings/UserAccesses/UserAccessProcessingService.Validations.cs
ISL.ReIdentification.Core/Services/Processings/UserAccesses/UserAccessProcessingService.cs
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server/Program.cs
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server/Program.cs

PROCESSINGS: User Access - Retrieve User Access By Id

---

ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/PdsDatas/PdsDataServiceTests.Exceptions.Add.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/PdsDatas/PdsDataServiceTests.Exceptions.Modify.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/PdsDatas/PdsDataServiceTests.Exceptions.OrganisationsHaveAccessToThisPatient.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/PdsDatas/PdsDataServiceTests.Exceptions.RemoveById.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/PdsDatas/PdsDataServiceTests.Exceptions.RetrieveAll.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/PdsDatas/PdsDataServiceTests.Exceptions.RetrieveById.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/PdsDatas/PdsDataServiceTests.Logic.Add.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/PdsDatas/PdsDataServiceTests.Logic.Modify.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/PdsDatas/PdsDataServiceTests.Logic.OrganisationsHaveAccessToThisPatient.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/PdsDatas/PdsDataServiceTests.Logic.RemoveById.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/PdsDatas/PdsDataServiceTests.Logic.RetrieveAll.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/PdsDatas/PdsDataServiceTests.Logic.RetrieveById.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/PdsDatas/PdsDataServiceTests.Validations.Add.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/PdsDatas/PdsDataServiceTests.Validations.Modify.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/PdsDatas/PdsDataServiceTests.Validations.OrganisationsHaveAccessToThisPatient.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/PdsDatas/PdsDataServiceTests.Validations.RemoveById.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/PdsDatas/PdsDataServiceTests.Validations.RetrieveById.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/PdsDatas/PdsDataServiceTests.cs
ISL.ReIdentification.Core/Services/Foundations/PdsDatas/IPdsDataService.cs
ISL.ReIdentification.Core/Services/Foundations/PdsDatas/PdsDataService.cs

MINOR FOUNDATIONS: Pds - OrganisationsHaveAccessToThisPatient

---

ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/package-lock.json
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Unit/Controllers/PdsDatas/PdsDataControllerTests.Exceptions.Get.cs
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Unit/Controllers/PdsDatas/PdsDataControllerTests.Exceptions.GetAll.cs
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Unit/Controllers/PdsDatas/PdsDataControllerTests.Exceptions.Post.cs
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Unit/Controllers/PdsDatas/PdsDataControllerTests.Exceptions.Put.cs
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Unit/Controllers/PdsDatas/PdsDataControllerTests.Logic.Get.cs
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Unit/Controllers/PdsDatas/PdsDataControllerTests.Logic.GetAll.cs
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Unit/Controllers/PdsDatas/PdsDataControllerTests.Logic.Post.cs
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Unit/Controllers/PdsDatas/PdsDataControllerTests.Logic.Put.cs
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Unit/Controllers/PdsDatas/PdsDataControllerTests.cs
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server/Controllers/PdsDataController.cs

CLOSES #AB16856
CLOSES #AB16879

CONTROLLERS: Pds - POST & PUT

---

ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Unit/Controllers/OdsDatas/OdsDataControllerTests.Exceptions.Delete.cs
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Unit/Controllers/OdsDatas/OdsDataControllerTests.Exceptions.Get.cs
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Unit/Controllers/OdsDatas/OdsDataControllerTests.Exceptions.GetAll.cs
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Unit/Controllers/OdsDatas/OdsDataControllerTests.Exceptions.GetAllChildren.cs
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Unit/Controllers/OdsDatas/OdsDataControllerTests.Exceptions.Post.cs
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Unit/Controllers/OdsDatas/OdsDataControllerTests.Exceptions.Put.cs
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Unit/Controllers/OdsDatas/OdsDataControllerTests.Logic.Delete.cs
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Unit/Controllers/OdsDatas/OdsDataControllerTests.Logic.Get.cs
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Unit/Controllers/OdsDatas/OdsDataControllerTests.Logic.GetAll.cs
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Unit/Controllers/OdsDatas/OdsDataControllerTests.Logic.GetAllChildren.cs
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Unit/Controllers/OdsDatas/OdsDataControllerTests.Logic.Post.cs
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Unit/Controllers/OdsDatas/OdsDataControllerTests.Logic.Put.cs
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Unit/Controllers/OdsDatas/OdsDataControllerTests.cs
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Unit/ISL.ReIdentification.Configurations.Server.Tests.Unit.csproj
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server/Controllers/OdsDataController.cs

CLOSES #AB16861
CLOSES #AB16862
CLOSES #AB16863

CONTROLLERS: Ods - All CRUD operations

---

ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/CsvIdentificationRequests/CsvIdentificationRequestTests.Validations.Add.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/CsvIdentificationRequests/CsvIdentificationRequestTests.Validations.Modify.cs
ISL.ReIdentification.Core/Services/Foundations/CsvIdentificationRequests/CsvIdentificationRequestService.Validations.cs

CLOSES #AB16864
CLOSES #AB16925

CODE RUB: CsvIdentificationRequest Add Validation for Filepath

---

ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/Documents/DocumentsTests.Exceptions.RetrieveDocumentByFileName.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/Documents/DocumentsTests.Logic.RetrieveDocumentByFileName.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/Documents/DocumentsTests.Validations.RetrieveDocumentByFileName.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/Documents/DocumentsTests.cs
ISL.ReIdentification.Core/Services/Foundations/Documents/DocumentService.Validations.cs
ISL.ReIdentification.Core/Services/Foundations/Documents/DocumentService.cs

FOUNDATIONS: Document RetrieveDocumentByFileName

---

ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Unit/Controllers/OdsDatas/OdsDataControllerTests.Exceptions.GetAllDescendants.cs
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Unit/Controllers/OdsDatas/OdsDataControllerTests.Logic.GetAllDescendants.cs
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server/Controllers/OdsDataController.cs

CONTROLLERS: Ods - GetAllDescendants

---

ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Acceptance/Apis/OdsDataApiTests.Logic.cs
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Acceptance/Apis/OdsDataApiTests.cs
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Acceptance/Brokers/ApiBroker.OdsData.cs
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Acceptance/Models/OdsDatas/OdsData.cs

ACCEPTANCE: Ods - PUT

---

ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Acceptance/Apis/OdsDataApiTests.Logic.cs
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Acceptance/Apis/OdsDataApiTests.cs

ACCEPTANCE: Ods - DELETE

---

ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Acceptance/Apis/OdsDataApiTests.Logic.cs
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Acceptance/Apis/OdsDataApiTests.cs

ACCEPTANCE: Ods - GET

---

ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Acceptance/Apis/OdsDataApiTests.Logic.cs
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Acceptance/Apis/OdsDataApiTests.cs

ACCEPTANCE: Ods - GET ALL

---

ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Acceptance/Apis/OdsDataApiTests.Logic.cs
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Acceptance/Apis/OdsDataApiTests.cs
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Acceptance/Brokers/ApiBroker.OdsData.cs
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server/Controllers/OdsDataController.cs

ACCEPTANCE: Ods - GetChildren

---

ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Acceptance/Apis/CsvIdentificationRequestApiTests.Logic.cs
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Acceptance/Apis/CsvIdentificationRequestApiTests.cs
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Acceptance/Brokers/ApiBroker.CsvIdentificationRequest.cs
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Acceptance/Models/CsvIdentificationRequests/CsvIdentificationRequest.cs

ACCEPTANCE: CsvIdentificationRequest All CRUD Operations

---

ISL.ReIdentification.Core.Tests.Unit/Services/Coordinations/Identifications/IdentificationCoordinationTests.Logic.ConvertCsvIdentificationRequestToIdentificationRequest.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Coordinations/Identifications/IdentificationCoordinationTests.Logic.ConvertIdentificationRequestToCsvIdentificationRequest.cs
ISL.ReIdentification.Core/Services/Coordinations/Identifications/IdentificationCoordinationService.cs
ISL.Reidentification.Core.Tests.Unit/Services/Coordinations/Identifications/IdentificationCoordinationTests.cs

MINOR-COORDINATIONS: Hydrate IdentificationRequest with user data

---

ISL.ReIdentification.Core.Tests.Unit/Services/Coordinations/Identifications/IdentificationCoordinationTests.Exceptions.PersistCsvIdentificationRequests.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Coordinations/Identifications/IdentificationCoordinationTests.Exceptions.PersistImpersonationContext.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Coordinations/Identifications/IdentificationCoordinationTests.Exceptions.ProcessCsvIdentificationRequests.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Coordinations/Identifications/IdentificationCoordinationTests.Exceptions.ProcessImpersonationContextRequest.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Coordinations/Identifications/IdentificationCoordinationTests.Logic.ConvertCsvIdentificationRequestToIdentificationRequest.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Coordinations/Identifications/IdentificationCoordinationTests.Logic.ConvertIdentificationRequestToCsvIdentificationRequest.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Coordinations/Identifications/IdentificationCoordinationTests.Logic.ExtractFromFilepath.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Coordinations/Identifications/IdentificationCoordinationTests.Logic.PersistCsvIdentificationRequests.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Coordinations/Identifications/IdentificationCoordinationTests.Logic.PersistImpersonationContext.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Coordinations/Identifications/IdentificationCoordinationTests.Logic.ProcessCsvIdentificationRequestAsync.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Coordinations/Identifications/IdentificationCoordinationTests.Logic.ProcessImpersonationContextRequest.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Coordinations/Identifications/IdentificationCoordinationTests.Validations.PersistCsvIdentificationRequests.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Coordinations/Identifications/IdentificationCoordinationTests.Validations.PersistImpersonationContext.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Coordinations/Identifications/IdentificationCoordinationTests.Validations.ProcessCsvIdentificationRequests.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Coordinations/Identifications/IdentificationCoordinationTests.Validations.ProcessImpersonationContextRequest.cs
ISL.ReIdentification.Core/Services/Coordinations/Identifications/IdentificationCoordinationService.cs
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Integration/Apis/ReIdentificationTests.ProcessCsvIdentificationRequestAsync.cs
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Integration/Apis/ReIdentificationTests.cs
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Integration/Brokers/ApiBroker.CsvIdentificationRequest.cs
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Integration/Brokers/ApiBroker.ReIdentification.cs
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server/Controllers/ReIdentificationController.cs
ISL.Reidentification.Core.Tests.Unit/Services/Coordinations/Identifications/IdentificationCoordinationTests.Exceptions.ProcessIdentificationRequests.cs
ISL.Reidentification.Core.Tests.Unit/Services/Coordinations/Identifications/IdentificationCoordinationTests.Logic.ProcessIdentificationRequests.cs
ISL.Reidentification.Core.Tests.Unit/Services/Coordinations/Identifications/IdentificationCoordinationTests.Validations.ProcessIdentificationRequests.cs
ISL.Reidentification.Core.Tests.Unit/Services/Coordinations/Identifications/IdentificationCoordinationTests.cs

INTEGRATIONS: Identification - Post CSV

---

ISL.ReIdentification.Core.Tests.Unit/Services/Coordinations/Identifications/IdentificationCoordinationTests.Logic.ProcessCsvIdentificationRequestAsync.cs
ISL.ReIdentification.Core/Services/Coordinations/Identifications/IdentificationCoordinationService.cs

MINOR-FIX: Identification Coordination Service filepath

---

ISL.ReIdentification.Core.Tests.Unit/Services/Orchestrations/Identifications/IdentificationOrchestrationTests.Exceptions.ProcessIdentificationRequest.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Orchestrations/Identifications/IdentificationOrchestrationTests.Logic.ProcessIdentificationRequest.cs
ISL.ReIdentification.Core/Brokers/Storages/Sql/ReIdentifications/ReidentificationStorageBroker.AccessAudit.Configurations.cs
ISL.ReIdentification.Core/Migrations/20241119122128_ModifyAccessAuditToAddTransactionId.Designer.cs
ISL.ReIdentification.Core/Migrations/20241119122128_ModifyAccessAuditToAddTransactionId.cs
ISL.ReIdentification.Core/Models/Foundations/AccessAudits/AccessAudit.cs
ISL.ReIdentification.Core/Services/Orchestrations/Identifications/IdentificationOrchestrationService.cs

Addition of transactionId to group audits within a transaction

ORCHESTRATIONS: Identification Orchestration Service - Process Identification Request

---

ISL.ReIdentification.Core/Brokers/Storages/Blob/BlobStorageBroker.cs
ISL.ReIdentification.Core/Brokers/Storages/Blob/IBlobStorageBroker.cs
ISL.ReIdentification.Core/ISL.ReIdentification.Core.csproj
ISL.ReIdentification.Core/Providers/Storage/FakeStorageProvider.cs
ISL.ReIdentification.Functions/Program.cs
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server/Program.cs
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server/Program.cs

BROKERS: Azure Storage - Implementing methods

---

ISL.ReIdentification.Functions/Program.cs
ISL.ReIdentification.Functions/PurgeReidentifiedRecordsThatHaveExpiredTimerFunction.cs

CODE RUB: Update Timer Function Di and Name

---

ISL.ReIdentification.Core/Services/Coordinations/Identifications/IIdentificationCoordinationService.cs
ISL.ReIdentification.Core/Services/Coordinations/Identifications/IdentificationCoordinationService.cs
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Unit/Controllers/ReIdentification/ReIdentificationControllerTests.Exceptions.PostImpersonationContextGenerateTokens.cs
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Unit/Controllers/ReIdentification/ReIdentificationControllerTests.Logic.PostImpersonationContextGenerateTokens.cs
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Unit/Controllers/ReIdentification/ReIdentificationControllerTests.Security.GetCsvIdentificationRequestById.cs
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Unit/Controllers/ReIdentification/ReIdentificationControllerTests.Security.PostIdentificationRequests.cs
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Unit/Controllers/ReIdentification/ReIdentificationControllerTests.Security.PostImpersonationContextGenerateTokens.cs
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Unit/Controllers/ReIdentification/ReIdentificationControllerTests.Security.PostImpersonationContextRequestAsync.cs
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server/Controllers/ReIdentificationController.cs

closes AB#17851
closes AB#18120

CONTROLLERS: ReIdentification - Generate Tokens

---

.github/workflows/validatepr.yml

CODE RUB: Updated script
closes [AB#18373](https://dev.azure.com/NELAnalytics/aef6c175-110f-4ba4-82fc-70761f459236/_workitems/edit/18373)
closes [AB#18361](https://dev.azure.com/NELAnalytics/aef6c175-110f-4ba4-82fc-70761f459236/_workitems/edit/18361)

CODE RUB: Updated script

---

.github/workflows/validatepr.yml

closes [AB#18373](https://dev.azure.com/NELAnalytics/aef6c175-110f-4ba4-82fc-70761f459236/_workitems/edit/18373)
closes [AB#18361](https://dev.azure.com/NELAnalytics/aef6c175-110f-4ba4-82fc-70761f459236/_workitems/edit/18361)

CODE RUB: script update

---

ISL.ReIdentification.Functions/appsettings.json

CLOSES [AB#18385](https://dev.azure.com/NELAnalytics/aef6c175-110f-4ba4-82fc-70761f459236/_workitems/edit/18385)

CODE RUB: Add Condig App Settings

---

ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/brokers/apiBroker.userAgreement.ts
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server/appsettings.json

closes [AB#18444](https://dev.azure.com/NELAnalytics/aef6c175-110f-4ba4-82fc-70761f459236/_workitems/edit/18444)

CodeRub: changing the handling of null ToS

---

ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/App.css
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/components/bases/layouts/BreadCrumb/BreadCrumbStyle.css
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/index.css
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/App.css
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/layouts/navbar.tsx
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/securitys/login.tsx
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/index.css

closes [AB#18410](https://dev.azure.com/NELAnalytics/aef6c175-110f-4ba4-82fc-70761f459236/_workitems/edit/18410)

CODE RUB: Remove Branding

---

ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server/ISL.ReIdentification.Configurations.Server.csproj
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server/Properties/launchSettings.json
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/breachDetails/BreachModal.tsx

closes [AB#18476](https://dev.azure.com/NELAnalytics/aef6c175-110f-4ba4-82fc-70761f459236/_workitems/edit/18476)

CODE RUB: random change

---

ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/vite.config.ts
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server/Properties/launchSettings.json

closes [AB#18476](https://dev.azure.com/NELAnalytics/aef6c175-110f-4ba4-82fc-70761f459236/_workitems/edit/18476)

CODE RUB: Fix Vite

---

ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server/Properties/launchSettings.json

closes [AB#18467](https://dev.azure.com/NELAnalytics/aef6c175-110f-4ba4-82fc-70761f459236/_workitems/edit/18467)

CODE RUB: Launch Settings

---

ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/ISL.ReIdentification.Configurations.Client.esproj
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/breachDetails/BreachDetails.tsx

closes [AB#18476](https://dev.azure.com/NELAnalytics/aef6c175-110f-4ba4-82fc-70761f459236/_workitems/edit/18476)

CODE RUB: Update line breaks

---

ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/App.css
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/core/menu.tsx
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/layouts/navbar.tsx
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/securitys/login.tsx
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/index.css

closes [AB#18410](https://dev.azure.com/NELAnalytics/aef6c175-110f-4ba4-82fc-70761f459236/_workitems/edit/18410)

CODE RUB: Update Branding

---

ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/components/layouts/loginUnauth.tsx
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/layouts/loginUnauth.tsx

Closes [AB#18410](https://dev.azure.com/NELAnalytics/aef6c175-110f-4ba4-82fc-70761f459236/_workitems/edit/18410)

CODE RUB: Login Screen Brand

---

ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server/ISL.ReIdentification.Configurations.Server.csproj

closes [AB#18487](https://dev.azure.com/NELAnalytics/aef6c175-110f-4ba4-82fc-70761f459236/_workitems/edit/18487)

CODE RUB: Lowercase Reference

---

ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/csvIdentificationWorklist/csvIdentificationWorklistRowView.tsx
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/csvReIdentification/csvReIdentificationDownloadDetail.tsx

closes [AB#18476](https://dev.azure.com/NELAnalytics/aef6c175-110f-4ba4-82fc-70761f459236/_workitems/edit/18476)

CODE RUB: Disable download if expired

---

ISL.ReIdentification.Functions/ProjectOutboxEventFunction.cs

Closes [AB#18487](https://dev.azure.com/NELAnalytics/aef6c175-110f-4ba4-82fc-70761f459236/_workitems/edit/18487)

CODE RUB: Remove function to save error logs

---

ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/Notifications/NotificationTests.Exceptions.SendImpersonationTokensGenerated.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/Notifications/NotificationTests.Logic.SendImpersonationTokenGeneratedNotification.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/Notifications/NotificationTests.Validations.SendImpersonationTokensGeneratedNotification.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/Notifications/NotificationTests.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Orchestrations/Persists/PersistanceOrchestrationServiceTests.Exceptions.SendGeneratedTokensNotification.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Orchestrations/Persists/PersistanceOrchestrationServiceTests.Logic.SendGeneratedTokensNotification.cs
ISL.ReIdentification.Core/Models/Brokers/Notifications/NotifyConfigurations.cs
ISL.ReIdentification.Core/Services/Foundations/Notifications/INotificationService.cs
ISL.ReIdentification.Core/Services/Foundations/Notifications/NotificationService.Validations.cs
ISL.ReIdentification.Core/Services/Foundations/Notifications/NotificationService.cs
ISL.ReIdentification.Core/Services/Orchestrations/Persists/PersistanceOrchestrationService.cs
ISL.ReIdentification.Functions/appsettings.json
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server/appsettings.json
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server/appsettings.json

closes [AB#18433](https://dev.azure.com/NELAnalytics/LondonDataService/_workitems/edit/18433)

FOUNDATIONS: Notifications SendImpersonationContextTokensGeneratedNotificationAsync

---

ISL.ReIdentification.Core/Migrations/20250106100109_ModifyImpersonationContextRemoveSecretFields.Designer.cs
ISL.ReIdentification.Core/Migrations/20250106100109_ModifyImpersonationContextRemoveSecretFields.cs

closes [AB#18128](https://dev.azure.com/NELAnalytics/LondonDataService/_workitems/edit/18128)

CODE RUB: Add migration to remove ClientSecret and ClientId fields

---

ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/ISL.ReIdentification.Configurations.Client.esproj
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/components/accessAudits/accessAuditRowView.tsx
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/components/accessAudits/accessAuditTable.tsx
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/components/layouts/loginUnauth.tsx
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/components/layouts/navbar.tsx
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/pages/home.tsx
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/vite.config.ts
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server/ISL.ReIdentification.Configurations.Server.csproj
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server/Properties/launchSettings.json
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/layouts/loginUnauth.tsx
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/layouts/navbar.tsx
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/reports/ReportsReasonPage.tsx
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/pages/home.tsx
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/pages/reidReportHome.tsx

Closes [AB#18410](https://dev.azure.com/NELAnalytics/aef6c175-110f-4ba4-82fc-70761f459236/_workitems/edit/18410)

CODE RUB: Branding updates with Wording

---

ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/core/menu.tsx
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/csvReIdentification/csvReIdentificationDetailCardView.tsx
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/reIdentification/reIdentificationDetailCardView.tsx
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Acceptance/Apis/FeaturesApiTests.Logic.cs
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server/appsettings.json

closes [AB#18629](https://dev.azure.com/NELAnalytics/aef6c175-110f-4ba4-82fc-70761f459236/_workitems/edit/18629)

CODE RUB: Better Errors on CSV Upload

---

ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/userAgreements/userAgreements.tsx
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/userAgreements/versions/agreement_v0_2.tsx
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/index.css

closes [AB#15354](https://dev.azure.com/NELAnalytics/aef6c175-110f-4ba4-82fc-70761f459236/_workitems/edit/15354)

CODE RUB: Update TOC Wording and make model wider

---

ISL.ReIdentification.Core/Brokers/Storages/Sql/ReIdentifications/ReidentificationStorageBroker.OdsData.Configurations.cs
ISL.ReIdentification.Core/Migrations/20250114160024_UpMaxLength.Designer.cs
ISL.ReIdentification.Core/Migrations/20250114160024_UpMaxLength.cs
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Unit/Controllers/OdsDatas/OdsDataControllerTests.Security.Get.cs
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Unit/Controllers/OdsDatas/OdsDataControllerTests.Security.GetAll.cs
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Unit/Controllers/PdsDatas/PdsDataControllerTests.Security.Get.cs
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Unit/Controllers/PdsDatas/PdsDataControllerTests.Security.GetAll.cs
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server/Controllers/OdsDataController.cs
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server/Controllers/PdsDataController.cs
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/userAgreements/agreementCatalogue.tsx
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/userAgreements/versions/agreement_v1_0.tsx
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server/appsettings.json

CLOSES [AB#16311](https://dev.azure.com/NELAnalytics/aef6c175-110f-4ba4-82fc-70761f459236/_workitems/edit/16311)

CODE RUB: Update Roles on ODS and PDS

---

ISL.ReIdentification.Core/Brokers/Storages/Sql/ReIdentifications/IReidentificationStorageBroker.Audit.cs
ISL.ReIdentification.Core/Brokers/Storages/Sql/ReIdentifications/ReidentificationStorageBroker.Audit.Configurations.cs
ISL.ReIdentification.Core/Brokers/Storages/Sql/ReIdentifications/ReidentificationStorageBroker.Audit.cs
ISL.ReIdentification.Core/Brokers/Storages/Sql/ReIdentifications/ReidentificationStorageBroker.cs
ISL.ReIdentification.Core/Migrations/20250116150954_AddAudit.Designer.cs
ISL.ReIdentification.Core/Migrations/20250116150954_AddAudit.cs
ISL.ReIdentification.Core/Models/Foundations/Audits/Audit.cs

closes [AB#18906](https://dev.azure.com/NELAnalytics/aef6c175-110f-4ba4-82fc-70761f459236/_workitems/edit/18906)

DATA: Audit

---

ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server/Controllers/AccessAuditsController.cs

Closes [AB#19100](https://dev.azure.com/NELAnalytics/aef6c175-110f-4ba4-82fc-70761f459236/_workitems/edit/19100)

CODE RUB: Remove Odata Paging on portal site for access Control

---

ISL.ReIdentification.Core.Tests.Unit/Services/Orchestrations/Identifications/IdentificationOrchestrationTests.Logic.ProcessIdentificationRequest.cs
ISL.ReIdentification.Core/Services/Orchestrations/Identifications/IdentificationOrchestrationService.cs
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/accessAudits/accessAuditTable.tsx

closes [AB#19657](https://dev.azure.com/NELAnalytics/aef6c175-110f-4ba4-82fc-70761f459236/_workitems/edit/19657)

CODE RUB: Change Count population

---

ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/breachDetails/BreachDetails.tsx
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/securitys/userProfile.tsx

closes [AB#19658](https://dev.azure.com/NELAnalytics/aef6c175-110f-4ba4-82fc-70761f459236/_workitems/edit/19658)

CODE RUB: Update OrgCode Style

---

ISL.ReIdentification.Core/Brokers/Securities/ISecurityBroker.cs
ISL.ReIdentification.Core/Brokers/Securities/SecurityBroker.cs
ISL.ReIdentification.Functions/Program.cs
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server/Controllers/AuditsController.cs
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server/Controllers/CsvIdentificationRequestController.cs
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server/Controllers/ImpersonationContextsController.cs
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server/Controllers/LookupsController.cs
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server/Controllers/OdsDataController.cs
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server/Controllers/PdsDataController.cs
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server/Controllers/UserAccessesController.cs
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server/ISL.ReIdentification.Configurations.Server.csproj
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server/appsettings.json
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server/Controllers/CsvIdentificationRequestController.cs
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server/Controllers/ImpersonationContextsController.cs
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server/Controllers/LookupsController.cs
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server/Controllers/OdsDataController.cs
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server/Controllers/PdsDataController.cs
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server/Controllers/UserAccessesController.cs
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server/Controllers/UserAgreementsController.cs
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server/ISL.ReIdentification.Portals.Server.csproj
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server/appsettings.json

Closes [AB#19744](https://dev.azure.com/NELAnalytics/aef6c175-110f-4ba4-82fc-70761f459236/_workitems/edit/19744)

BROKERS: Security Broker Changes To Support Manage Identity Usage

---

ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/UserAgreements/UserAgreementServiceTests.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Orchestrations/Persists/PersistanceOrchestrationServiceTests.Logic.PurgeCsvReIdentificationRecordsThatExpired.cs
ISL.ReIdentification.Core/Services/Orchestrations/Persists/PersistanceOrchestrationService.cs

closes [AB#19743](https://dev.azure.com/NELAnalytics/aef6c175-110f-4ba4-82fc-70761f459236/_workitems/edit/19743)

CODE RUB: Update Purge CreatedBy and Check

---

ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server/ISL.ReIdentification.Configurations.Server.csproj
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server/Program.cs
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server/appsettings.json
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Integration/ISL.ReIdentification.Portals.Server.Tests.Integration.ReIdentification.csproj
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server/ISL.ReIdentification.Portals.Server.csproj
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server/Program.cs
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server/appsettings.json

closes [AB#20022](https://dev.azure.com/NELAnalytics/aef6c175-110f-4ba4-82fc-70761f459236/_workitems/edit/20022)

PROVIDERS: Implemented Demo Data Provider

---

ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/components/odsData/odsTable.tsx
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/components/pdsData/pdsTable.tsx
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/services/views/odsData/odsDataViewService.ts
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/services/views/pdsData/pdsDataViewService.ts
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/securitys/userProfile.tsx
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/userAgreements/userAgreements.tsx
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/userAgreements/versions/agreement_v1_0.tsx
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/index.css

closes [AB#20018](https://dev.azure.com/NELAnalytics/aef6c175-110f-4ba4-82fc-70761f459236/_workitems/edit/20018)

CODE RUB: Terms and Conditions Update

---

ISL.ReIdentification.Core.Tests.Unit/Services/Coordinations/Identifications/IdentificationCoordinationTests.Logic.ConvertCsvIdentificationRequestToIdentificationRequest.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Orchestrations/Identifications/IdentificationOrchestrationTests.Logic.ProcessIdentificationRequest.cs
ISL.ReIdentification.Core/Services/Coordinations/Identifications/IdentificationCoordinationService.cs
ISL.ReIdentification.Core/Services/Orchestrations/Identifications/IdentificationOrchestrationService.cs
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/reIdentification/reIdentificationDetailCardView.tsx

closes [AB#20064](https://dev.azure.com/NELAnalytics/aef6c175-110f-4ba4-82fc-70761f459236/_workitems/edit/20064)

CODE RUB: Add Leading Zero When needed

---

ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/package-lock.json
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/package.json
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/reports/reportToast.tsx
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/reports/reportsHome.tsx
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/reports/reportsLaunchPage.tsx
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/hooks/useReidentification.ts
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/services/foundations/reIdentificationService.ts

close [AB#20067](https://dev.azure.com/NELAnalytics/aef6c175-110f-4ba4-82fc-70761f459236/_workitems/edit/20067)
- Toast on error
- Toast on inital re-id attempt

report page improvements

---

ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/services/views/userAccess/userAccessViewService.ts
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/brokers/apiBroker.userAgreement.ts
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/services/views/csvIdentificationRequest/csvIdentificationRequestViewService.ts
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/services/views/userAccess/userAccessViewService.ts

closes [AB#20134](https://dev.azure.com/NELAnalytics/aef6c175-110f-4ba4-82fc-70761f459236/_workitems/edit/20134)

CODE RUB: Update EntraIds to strings

---

ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server/Controllers/UserAccessesController.cs
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/userAgreements/userAgreements.tsx

closes [AB#20018](https://dev.azure.com/NELAnalytics/aef6c175-110f-4ba4-82fc-70761f459236/_workitems/edit/20018)

CODE RUB: User Agreement Text Hide

---

ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/breachDetails/BreachDetails.tsx
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/csvReIdentification/csvReIdentificationDetailCardView.tsx

closes [AB#20015](https://dev.azure.com/NELAnalytics/aef6c175-110f-4ba4-82fc-70761f459236/_workitems/edit/20015)

CODE RUB: Change check to max 10 numbers and numberical

---

ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/reports/reportsLaunchPage.tsx
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/userAgreements/versions/agreement_v1_0.tsx
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/errors/error.tsx
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/pages/reidReportHome.tsx

closes [AB#20196](https://dev.azure.com/NELAnalytics/aef6c175-110f-4ba4-82fc-70761f459236/_workitems/edit/20196)
closes [AB#20194](https://dev.azure.com/NELAnalytics/aef6c175-110f-4ba4-82fc-70761f459236/_workitems/edit/20194)
closes [AB#20192](https://dev.azure.com/NELAnalytics/aef6c175-110f-4ba4-82fc-70761f459236/_workitems/edit/20192)

CODE RUB: Check Visible Pages

---

ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/AccessAudit/AccessAuditsTests.Exceptions.BulkAdd.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/AccessAudit/AccessAuditsTests.Logic.BulkAdd.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/AccessAudit/AccessAuditsTests.Validations.BulkAdd.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/AccessAudit/AccessAuditsTests.cs
ISL.ReIdentification.Core/Brokers/Storages/Sql/ReIdentifications/IReidentificationStorageBroker.AccessAudit.cs
ISL.ReIdentification.Core/Brokers/Storages/Sql/ReIdentifications/ReidentificationStorageBroker.AccessAudit.cs
ISL.ReIdentification.Core/Services/Foundations/AccessAudits/AccessAuditService.Exceptions.cs
ISL.ReIdentification.Core/Services/Foundations/AccessAudits/AccessAuditService.Validations.cs
ISL.ReIdentification.Core/Services/Foundations/AccessAudits/AccessAuditService.cs
ISL.ReIdentification.Core/Services/Foundations/AccessAudits/IAccessAuditService.cs
ISL.Reidentification.Core.Tests.Unit/Services/Foundations/AccessAudit/AccessAuditsTests.cs

closes [AB#20318](https://dev.azure.com/NELAnalytics/aef6c175-110f-4ba4-82fc-70761f459236/_workitems/edit/20318)

FOUNDATIONS: Access Audit - Bulk Add

---

ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/breachDetails/BreachModal.tsx
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/hooks/useFileChange.ts

Closes [AB#20341](https://dev.azure.com/NELAnalytics/aef6c175-110f-4ba4-82fc-70761f459236/_workitems/edit/20341)

CODE RUB: Chunking on React FileUpload

---

ISL.ReIdentification.Core.Tests.Unit/ISL.ReIdentification.Core.Tests.Unit.csproj
ISL.ReIdentification.Infrastructure/ISL.ReIdentification.Infrastructure.csproj
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Acceptance/ISL.ReIdentification.Configurations.Server.Tests.Acceptance.csproj
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Unit/ISL.ReIdentification.Configurations.Server.Tests.Unit.csproj
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Acceptance/ISL.ReIdentification.Portals.Server.Tests.Acceptance.csproj
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Integration/ISL.ReIdentification.Portals.Server.Tests.Integration.ReIdentification.csproj
ISL.Reidentification.Core.Tests.Unit/ISL.ReIdentification.Core.Tests.Unit.csproj
ISL.Reidentification.Infrastructure/ISL.ReIdentification.Infrastructure.csproj
ISL.Reidentification.WebApps.Configurations/ISL.Reidentification.Configurations.Server.Tests.Acceptance/ISL.ReIdentification.Configurations.Server.Tests.Acceptance.csproj

CODE RUB: Updated packages - AdotNet

---

ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/brokers/apiBroker.frontendConfigurationBroker.ts
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/csvReIdentification/csvReIdentificationDetailCardView.tsx
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/hooks/useFileChange.ts
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server/appsettings.json

closes [AB#20367](https://dev.azure.com/NELAnalytics/aef6c175-110f-4ba4-82fc-70761f459236/_workitems/edit/20367)

CODE RUB: Add CSV Upload Limit

---

ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/brokers/apiBroker.frontendConfigurationBroker.ts
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/hooks/useFileChange.ts

Closes [AB#20367](https://dev.azure.com/NELAnalytics/aef6c175-110f-4ba4-82fc-70761f459236/_workitems/edit/20367)

CODE RUB: Update frontend config

---

ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/reports/reportsLaunchPage.tsx
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/hooks/useFrontendConfiguration.ts
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/hooks/useReidentification.ts

Closes [AB#20383](https://dev.azure.com/NELAnalytics/aef6c175-110f-4ba4-82fc-70761f459236/_workitems/edit/20383)

FRONTEND: Block on excessive requests

---

ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/reports/reportToast.tsx
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/reports/reportsLaunchPage.tsx

Closes [AB#20385](https://dev.azure.com/NELAnalytics/aef6c175-110f-4ba4-82fc-70761f459236/_workitems/edit/20385)

FRONTEND: Copy / Paste rework

---

ISL.ReIdentification.Core.Tests.Unit/ISL.ReIdentification.Core.Tests.Unit.csproj
ISL.ReIdentification.Functions/ISL.ReIdentification.Functions.csproj
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Acceptance/ISL.ReIdentification.Configurations.Server.Tests.Acceptance.csproj
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Unit/ISL.ReIdentification.Configurations.Server.Tests.Unit.csproj
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Acceptance/ISL.ReIdentification.Portals.Server.Tests.Acceptance.csproj
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Integration/ISL.ReIdentification.Portals.Server.Tests.Integration.ReIdentification.csproj
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Unit/ISL.ReIdentification.Portals.Server.Tests.Unit.csproj
ISL.Reidentification.Core.Tests.Unit/ISL.ReIdentification.Core.Tests.Unit.csproj
ISL.Reidentification.Functions/ISL.ReIdentification.Functions.csproj
ISL.Reidentification.WebApps.Configurations/ISL.Reidentification.Configurations.Server.Tests.Acceptance/ISL.ReIdentification.Configurations.Server.Tests.Acceptance.csproj

CONFIG: Package upgrades

---

ISL.Reidentification.Core/ISL.ReIdentification.Core.csproj
ISL.Reidentification.Functions/ISL.ReIdentification.Functions.csproj

CONFIG: EF Upgrade

---

ISL.Reidentification.Core/ISL.ReIdentification.Core.csproj
ISL.Reidentification.Functions/ISL.ReIdentification.Functions.csproj

CONFIG: Efxceptions Upgrade

---

ISL.ReIdentification.Core/Brokers/Storages/Sql/ReIdentifications/ReidentificationStorageBroker.PdsData.Configurations.cs
ISL.ReIdentification.Core/Migrations/20250226123146_UpdatePseudoNhsNumber.Designer.cs
ISL.ReIdentification.Core/Migrations/20250226123146_UpdatePseudoNhsNumber.cs

closes [AB#20508](https://dev.azure.com/NELAnalytics/aef6c175-110f-4ba4-82fc-70761f459236/_workitems/edit/20508)

CODE RUB: Update Pseudo to 15 characters from 10

---

ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/csvReIdentification/csvReIdentificationDownloadDetail.tsx
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/reIdentification/reIdentificationDetailCardView.tsx
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/services/foundations/reIdentificationService.ts

closes [AB#20502](https://dev.azure.com/NELAnalytics/aef6c175-110f-4ba4-82fc-70761f459236/_workitems/edit/20502)

CODE RUB: add custom error for 401

---

ISL.ReIdentification.Core.Tests.Unit/ISL.ReIdentification.Core.Tests.Unit.csproj
ISL.ReIdentification.Core/ISL.ReIdentification.Core.csproj
ISL.ReIdentification.Functions/ISL.ReIdentification.Functions.csproj
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Acceptance/ISL.ReIdentification.Configurations.Server.Tests.Acceptance.csproj
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Unit/ISL.ReIdentification.Configurations.Server.Tests.Unit.csproj
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server/ISL.ReIdentification.Configurations.Server.csproj
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Acceptance/ISL.ReIdentification.Portals.Server.Tests.Acceptance.csproj
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Integration/ISL.ReIdentification.Portals.Server.Tests.Integration.ReIdentification.csproj
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Unit/ISL.ReIdentification.Portals.Server.Tests.Unit.csproj
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server/ISL.ReIdentification.Portals.Server.csproj
ISL.Reidentification.Core.Tests.Unit/ISL.ReIdentification.Core.Tests.Unit.csproj

closes [AB#20477](https://dev.azure.com/NELAnalytics/aef6c175-110f-4ba4-82fc-70761f459236/_workitems/edit/20477)

CODE RUB:  Update providers

---

azure-pipelines.yml

closes [AB#20491](https://dev.azure.com/NELAnalytics/aef6c175-110f-4ba4-82fc-70761f459236/_workitems/edit/20491)

infra: adding release tags to build

---

azure-pipelines.yml

closes [AB#20569](https://dev.azure.com/NELAnalytics/aef6c175-110f-4ba4-82fc-70761f459236/_workitems/edit/20569)

Coderub: update build name in pipelines

---

ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/components/core/copyIcon.tsx
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/components/pdsData/pdsRowView.tsx
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/components/pdsData/pdsTable.tsx
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/helpers/hxHelpers.ts
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client/src/services/views/pdsData/pdsDataViewService.ts

closes [AB#20546](https://dev.azure.com/NELAnalytics/aef6c175-110f-4ba4-82fc-70761f459236/_workitems/edit/20546)
Change filter to and = from a contains
Remove redundant col
add copy button

CODE RUB: Updates to PDS Page on Management Portal

---

ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/hooks/useFileChange.ts

Closes [AB#20628](https://dev.azure.com/NELAnalytics/aef6c175-110f-4ba4-82fc-70761f459236/_workitems/edit/20628)

CODE RUB: Update to check Header

---

ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/Lookups/LookupServiceTests.cs
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Unit/Controllers/Lookups/LookupsControllerTests.cs
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Unit/Controllers/Lookups/LookupsControllerTests.cs

CODE RUB: Fix build issues

---

ISL.ReIdentification.Core/ISL.ReIdentification.Core.csproj
ISL.ReIdentification.Functions/ISL.ReIdentification.Functions.csproj
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server/ISL.ReIdentification.Configurations.Server.csproj
ISL.Reidentification.Core/ISL.ReIdentification.Core.csproj
ISL.Reidentification.WebApps.Configurations/ISL.Reidentification.Configurations.Server/ISL.ReIdentification.Configurations.Server.csproj

RELEASES: v1.0.0.1

---

ISL.ReIdentification.Functions/ProjectOutboxEventFunction.cs

closes [AB#19188](https://dev.azure.com/NELAnalytics/LondonDataService/_workitems/edit/19188)

ProjectOutboxEventFunction -> Initial test implementation

---

ISL.ReIdentification.Functions/ProjectOutboxEventFunction.cs

closes [AB#20711](https://dev.azure.com/NELAnalytics/LondonDataService/_workitems/edit/20711)

CODE RUB: Testing Azure Function HttpTrigger handshake validation for event subscription

---

ISL.ReIdentification.Functions/Program.cs

closes [AB#20711](https://dev.azure.com/NELAnalytics/LondonDataService/_workitems/edit/20711)

CODE RUB: Add missing services to Program.cs

---

ISL.ReIdentification.Functions/Program.cs
ISL.ReIdentification.Functions/appsettings.json

closes [AB#20711](https://dev.azure.com/NELAnalytics/LondonDataService/_workitems/edit/20711)

CODE RUB: Add ReIdentificationProviderOfflineMode to appsettings

---

ISL.ReIdentification.Functions/ProjectOutboxEventFunction.cs

closes [AB#20740](https://dev.azure.com/NELAnalytics/LondonDataService/_workitems/edit/20740)

CODE RUB: Update validation response object

---

ISL.ReIdentification.Functions/ProjectOutboxEventFunction.cs

closes [AB#20740](https://dev.azure.com/NELAnalytics/LondonDataService/_workitems/edit/20740)

CODE RUB: Fix casing in validationResponse

---

ISL.ReIdentification.Functions/ProjectOutboxEventFunction.cs

closes [AB#20740](https://dev.azure.com/NELAnalytics/LondonDataService/_workitems/edit/20740)

CODE RUB: Add additonal logging to Azure Function

---

ISL.ReIdentification.Core/ISL.ReIdentification.Core.csproj
ISL.ReIdentification.Core/Services/Coordinations/Identifications/IdentificationCoordinationService.cs
ISL.ReIdentification.Functions/ISL.ReIdentification.Functions.csproj
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Acceptance/ISL.ReIdentification.Configurations.Server.Tests.Acceptance.csproj
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Integration/ISL.ReIdentification.Configurations.Server.Tests.Integration.csproj
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server.Tests.Unit/ISL.ReIdentification.Configurations.Server.Tests.Unit.csproj
ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Server/ISL.ReIdentification.Configurations.Server.csproj
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Acceptance/ISL.ReIdentification.Portals.Server.Tests.Acceptance.csproj
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Integration/ISL.ReIdentification.Portals.Server.Tests.Integration.csproj
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Unit/ISL.ReIdentification.Portals.Server.Tests.Unit.csproj
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server/ISL.ReIdentification.Portals.Server.csproj

closes [AB#20774](https://dev.azure.com/NELAnalytics/LondonDataService/_workitems/edit/20774)

CODE RUB: Fix TypeLoadException

---

ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/impersonationContext/impersonationContextDetailManage.tsx
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/models/impersonationContext/impersonationContext.ts

closes [AB#20803](https://dev.azure.com/NELAnalytics/aef6c175-110f-4ba4-82fc-70761f459236/_workitems/edit/20803)

CODE RUB: Update naming

---

ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/brokers/apiBroker.frontendConfigurationBroker.ts
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/impersonationContext/impersonationContextDetailManage.tsx
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server.Tests.Unit/Controllers/ImpersonationContexts/ImpersonationContextsControllerTests.Security.Get.cs
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server/Controllers/ImpersonationContextsController.cs
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server/appsettings.json

Closes [AB#20825](https://dev.azure.com/NELAnalytics/aef6c175-110f-4ba4-82fc-70761f459236/_workitems/edit/20825)

CODE RUB: Product 5 Usability fixes

---

ISL.ReIdentification.Core/Services/Coordinations/Identifications/IdentificationCoordinationService.cs
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/impersonationContext/impersonationContextDetailAdd.tsx
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/impersonationContext/impersonationContextProjectRowView.tsx
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/reports/ReportsReasonPage.tsx
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/reports/reportsHome.tsx
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/services/foundations/reIdentificationService.ts

Closes [AB#20985](https://dev.azure.com/NELAnalytics/aef6c175-110f-4ba4-82fc-70761f459236/_workitems/edit/20985)

CODE RUB: Report Url Error Handling

---

ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/impersonationContext/impersonationContextDetailAdd.tsx
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/impersonationContext/impersonationContextDetailManage.tsx
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/services/foundations/impersonationContextService.ts

Closes [AB#20985](https://dev.azure.com/NELAnalytics/aef6c175-110f-4ba4-82fc-70761f459236/_workitems/edit/20985)

CODE RUB: Ui Updates

---

ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/impersonationContext/impersonationContextDetailAdd.tsx
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/impersonationContext/impersonationContextProjectRowView.tsx
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/impersonationContext/impersonationContextProjectTable.tsx
ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client/src/components/userAccessSearch/userAccessSearch.tsx

closes [AB#20986](https://dev.azure.com/NELAnalytics/aef6c175-110f-4ba4-82fc-70761f459236/_workitems/edit/20986)

CODE RUB: Bugs and word changes from Testing

---

ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/Documents/DocumentsTests.Validations.AddDocument.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/Documents/DocumentsTests.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Orchestrations/Identifications/IdentificationOrchestrationTests.Validations.AddDocument.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Orchestrations/Identifications/IdentificationOrchestrationTests.cs
ISL.ReIdentification.Core/Services/Coordinations/Identifications/IdentificationCoordinationService.cs
ISL.ReIdentification.Core/Services/Foundations/Documents/DocumentService.Validations.cs
ISL.ReIdentification.Core/Services/Orchestrations/Identifications/IdentificationOrchestrationService.Validations.cs

fixes [AB#21228](https://dev.azure.com/NELAnalytics/LondonDataService/_workitems/edit/21228)

BUGFIX: Handle empty files

---

ISL.ReIdentification.Core/ISL.ReIdentification.Core.csproj

closes [AB#21291](https://dev.azure.com/NELAnalytics/LondonDataService/_workitems/edit/21291)

CODE RUB: Update storage provider version

---

ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/AccessAudit/AccessAuditsTests.Exceptions.Add.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/AccessAudit/AccessAuditsTests.Exceptions.BulkAdd.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/AccessAudit/AccessAuditsTests.Exceptions.Modify.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/AccessAudit/AccessAuditsTests.Exceptions.RemoveById.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/AccessAudit/AccessAuditsTests.Exceptions.RetrieveAll.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/AccessAudit/AccessAuditsTests.Exceptions.RetrieveById.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/AccessAudit/AccessAuditsTests.Logic.Add.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/AccessAudit/AccessAuditsTests.Logic.BulkAdd.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/AccessAudit/AccessAuditsTests.Logic.Modify.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/AccessAudit/AccessAuditsTests.Logic.RemoveById.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/AccessAudit/AccessAuditsTests.Logic.RetrieveAll.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/AccessAudit/AccessAuditsTests.Logic.RetrieveById.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/AccessAudit/AccessAuditsTests.Validations.Add.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/AccessAudit/AccessAuditsTests.Validations.BulkAdd.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/AccessAudit/AccessAuditsTests.Validations.Modify.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/AccessAudit/AccessAuditsTests.Validations.RemoveById.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/AccessAudit/AccessAuditsTests.Validations.RetrieveById.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/AccessAudit/AccessAuditsTests.cs
ISL.ReIdentification.Core/Services/Foundations/AccessAudits/AccessAuditService.Validations.cs
ISL.ReIdentification.Core/Services/Foundations/AccessAudits/AccessAuditService.cs

fixes [AB#22058](https://dev.azure.com/NELAnalytics/aef6c175-110f-4ba4-82fc-70761f459236/_workitems/edit/22058)

CODE RUB: Access Audit Security Audit Delete

---

ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/UserAccesses/UserAccessesTests.Logic.RemoveById.cs
ISL.ReIdentification.Core/Services/Foundations/UserAccesses/UserAccessService.cs

fixes [AB#22057](https://dev.azure.com/NELAnalytics/aef6c175-110f-4ba4-82fc-70761f459236/_workitems/edit/22057)

CODE RUB: User Access ApplyDeleteAudit 

---

ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/Lookups/LookupServiceTests.Logic.ApplyModifyAudit.cs
ISL.ReIdentification.Core.Tests.Unit/Services/Foundations/Lookups/LookupServiceTests.Logic.RemoveById.cs
ISL.ReIdentification.Core/Services/Foundations/Lookups/LookupService.Validations.cs
ISL.ReIdentification.Core/Services/Foundations/Lookups/LookupService.cs

fixes [AB#22071](https://dev.azure.com/NELAnalytics/aef6c175-110f-4ba4-82fc-70761f459236/_workitems/edit/22071)

CODE RUB: Lookup Security Audit Delete
